version: '3.8'

services:
  backend:
    build:
      context: ./ISME_BE
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=db;Database=IndividualBusiness;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./ISMS_FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:80
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge