// <auto-generated />
using System;
using AppBackend.BusinessObjects.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBackend.BusinessObjects.Migrations
{
    [DbContext(typeof(IndividualBusinessContext))]
    partial class IndividualBusinessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id")
                        .HasName("PK__Activity__3214EC0727D45608");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BankId")
                        .HasName("PK__Banks__AA08CB1327568829");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.BankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.HasKey("BankAccountId")
                        .HasName("PK__BankAcco__4FC8E4A1B506C46A");

                    b.HasIndex(new[] { "BankId", "AccountNumber" }, "UQ_BankAccounts_BankId_AccountNumber")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("IsCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsEnterprise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVendor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D8CD52BD2B");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Good", b =>
                {
                    b.Property<string>("GoodsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("FixedPurchasePrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("GoodsGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIncludeVat")
                        .HasColumnType("bit")
                        .HasColumnName("IsIncludeVAT");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemOnHand")
                        .HasColumnType("int");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("QuarantineOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vatrate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("10")
                        .HasColumnName("VATRate")
                        .IsFixedLength();

                    b.HasKey("GoodsId")
                        .HasName("PK__Goods__663DA92037CD9BDB");

                    b.HasIndex("GoodsGroupId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.GoodsCategory", b =>
                {
                    b.Property<string>("GoodsGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoodsGroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.HasKey("GoodsGroupId")
                        .HasName("PK__GoodsCat__609AEEF9ABA69ABD");

                    b.ToTable("GoodsCategory", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.OpenBank", b =>
                {
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DebitAmount0")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Debit_Amount0");

                    b.Property<string>("Properties")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CreateDate")
                        .HasName("PK__OpenBank__CE101B31A6C7E435");

                    b.ToTable("OpenBank", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.OpenCash", b =>
                {
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DebitAmount0")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Debit_Amount0");

                    b.Property<string>("Properties")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CreateDate")
                        .HasName("PK__OpenCash__CE101B31E474E686");

                    b.ToTable("OpenCash", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.OpenCustomer", b =>
                {
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("CustomerCreditAmount0")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("CustomerDebitAmount0")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Properties")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("VendorCreditAmount0")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("VendorDebitAmount0")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("VoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CreateDate")
                        .HasName("PK__OpenCust__CE101B31996A32C5");

                    b.ToTable("OpenCustomer", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.OpenInventory", b =>
                {
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DebitAmount0")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Debit_Amount0");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Properties")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CreateDate")
                        .HasName("PK__OpenInve__CE101B318F81FB3E");

                    b.ToTable("OpenInventory", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.StockTakeDetail", b =>
                {
                    b.Property<int>("StockTakeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeDetailId"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BookQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DifferenceQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GoodsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StockTakeVoucherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StockTakeDetailId")
                        .HasName("PK__StockTak__6F1159AAD61EF5A1");

                    b.HasIndex("StockTakeVoucherId");

                    b.ToTable("StockTakeDetails");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.StockTakeVoucher", b =>
                {
                    b.Property<string>("StockTakeVoucherId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Member1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Member2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Member3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StockTakeDate")
                        .HasColumnType("date");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("VoucherDate")
                        .HasColumnType("date");

                    b.HasKey("StockTakeVoucherId")
                        .HasName("PK__StockTak__604670B9049D1F92");

                    b.ToTable("StockTakeVouchers");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Unit1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Unit");

                    b.HasKey("Id")
                        .HasName("PK__Units__3214EC078DC82582");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IdcardNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("IDCardNumber");

                    b.Property<decimal?>("InssuranceSalary")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("NegotiatedSalary")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("NumberOfDependent")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C6B23FC29");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Voucher", b =>
                {
                    b.Property<string>("VoucherId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VoucherID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvoiceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pic")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("PIC");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("VoucherDate")
                        .HasColumnType("date");

                    b.Property<string>("VoucherDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VoucherId")
                        .HasName("PK__Voucher__3AEE79C18E9DB7D5");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.VoucherCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BelongToScreen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreditAccount1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreditAccount2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DebitAccount1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DebitAccount2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VoucherCode1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("VoucherCode");

                    b.HasKey("Id")
                        .HasName("PK__VoucherC__3214EC07F12EAABE");

                    b.ToTable("VoucherCodes");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.VoucherDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount1")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Amount2")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreditAccount1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreditAccount2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DebitAccount1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DebitAccount2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoodsName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OffsetVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Promotion")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RootCause")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SourceVoucherDetailId")
                        .HasColumnType("int");

                    b.Property<string>("SourceVoucherId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StockBucket")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("UserID");

                    b.Property<string>("VoucherId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VoucherID");

                    b.HasKey("Id")
                        .HasName("PK__VoucherD__3214EC07265E235B");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherDetail", (string)null);
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ActivityLog", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ActivityLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Good", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.GoodsCategory", "GoodsGroup")
                        .WithMany("Goods")
                        .HasForeignKey("GoodsGroupId")
                        .HasConstraintName("FK_Goodss_GoodsGroups");

                    b.Navigation("GoodsGroup");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.StockTakeDetail", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.StockTakeVoucher", "StockTakeVoucher")
                        .WithMany("StockTakeDetails")
                        .HasForeignKey("StockTakeVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StockTakeDetails_Voucher");

                    b.Navigation("StockTakeVoucher");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.VoucherDetail", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Voucher", "Voucher")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("FK_Detail_Header");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.GoodsCategory", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.StockTakeVoucher", b =>
                {
                    b.Navigation("StockTakeDetails");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Voucher", b =>
                {
                    b.Navigation("VoucherDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
