// ============================================================
//  shared/styles/sale.styles.ts
//  Style object for sale + import features — Premium refresh
// ============================================================

import React from "react";

const styles: Record<string, React.CSSProperties> = {
  // ── Layout ────────────────────────────────────────────────
  container: {
    maxWidth: "100%",
    margin: "0 auto",
    padding: "28px 32px",
    fontFamily:
      "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
    fontSize: 14,
    color: "#1e293b",
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 4,
    background: "linear-gradient(90deg, #7c3aed, #4f46e5)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    letterSpacing: "-0.3px",
  },
  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 14,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  hr: {
    border: "none",
    borderTop: "1px solid #e2e8f0",
    margin: "20px 0",
  },

  // ── Form fields ───────────────────────────────────────────
  fieldGroup: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 12,
  },
  label: {
    minWidth: 120,
    color: "#64748b",
    fontWeight: 500,
    fontSize: 13,
  },
  input: {
    flex: 1,
    padding: "8px 12px",
    border: "1.5px solid #e2e8f0",
    borderRadius: 8,
    fontSize: 14,
    color: "#1e293b",
    background: "#fff",
    transition: "border-color 0.15s, box-shadow 0.15s",
    outline: "none",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    fontSize: 14,
    color: "#374151",
    gap: 6,
    padding: "8px 16px",
    borderRadius: 8,
    border: "1.5px solid #e2e8f0",
    background: "#f8faff",
    fontWeight: 500,
    transition: "all 0.15s",
  },

  // ── Item table ────────────────────────────────────────────
  itemTable: {
    width: "100%",
    tableLayout: "fixed",
    borderCollapse: "collapse",
    fontSize: 12,
    border: "none",
  },
  itemTh: {
    padding: "10px 8px",
    background: "linear-gradient(135deg, #6d28d9, #4f46e5)",
    color: "#fff",
    textAlign: "left",
    fontWeight: 600,
    fontSize: 11,
    whiteSpace: "nowrap",
    borderBottom: "none",
    overflow: "hidden",
    letterSpacing: "0.04em",
  },
  itemTd: {
    padding: "6px 6px",
    borderBottom: "1px solid #f1f5f9",
    verticalAlign: "middle",
    fontSize: 12,
    overflow: "hidden",
  },
  inputTable: {
    width: "100%",
    padding: "5px 7px",
    border: "1.5px solid #e2e8f0",
    borderRadius: 5,
    fontSize: 12,
    boxSizing: "border-box",
    outline: "none",
    background: "#fff",
    color: "#1e293b",
    transition: "border-color 0.15s",
  },
  selectVat: {
    padding: "5px 6px",
    border: "1.5px solid #e2e8f0",
    borderRadius: 5,
    fontSize: 12,
    background: "#fff",
    cursor: "pointer",
    width: "100%",
    color: "#1e293b",
  },
  spinner: {
    position: "absolute",
    right: 8,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: 13,
    pointerEvents: "none",
  },

  // ── Summary box ───────────────────────────────────────────
  summaryBox: {
    marginTop: 16,
    border: "1.5px solid #ddd6fe",
    borderRadius: 12,
    padding: "16px 20px",
    background: "linear-gradient(135deg, #faf5ff, #eff6ff)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    maxWidth: 380,
    marginLeft: "auto",
    boxShadow: "0 2px 12px rgba(109,40,217,0.07)",
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 14,
    color: "#475569",
  },
  summaryTotal: {
    borderTop: "1.5px solid #ddd6fe",
    paddingTop: 10,
    marginTop: 4,
    fontSize: 16,
    fontWeight: 700,
    color: "#6d28d9",
  },

  // ── Dropdown portal ───────────────────────────────────────
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 14px",
    cursor: "pointer",
    fontSize: 13,
    borderBottom: "1px solid #f1f5f9",
    transition: "background 0.1s",
  },
  dropdownId: {
    fontWeight: 700,
    color: "#6d28d9",
    minWidth: 70,
    fontSize: 12,
  },
  dropdownName: { flex: 1, color: "#1e293b" },
  dropdownMeta: { fontSize: 11, color: "#94a3b8", whiteSpace: "nowrap" },

  // ── Buttons ───────────────────────────────────────────────
  btnPrimary: {
    padding: "10px 24px",
    background: "linear-gradient(135deg, #7c3aed, #4f46e5)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    boxShadow: "0 4px 14px rgba(109,40,217,0.35)",
    transition: "transform 0.15s, box-shadow 0.15s",
    letterSpacing: "0.02em",
  },
  btnSecondary: {
    padding: "8px 16px",
    background: "#f8faff",
    border: "1.5px solid #e2e8f0",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    color: "#475569",
    transition: "background 0.15s",
  },
  btnDanger: {
    padding: "4px 8px",
    background: "#fff1f2",
    color: "#dc2626",
    border: "1.5px solid #fecaca",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 600,
    transition: "background 0.15s",
  },
  btnDetail: {
    padding: "4px 8px",
    background: "#f0fdf4",
    color: "#16a34a",
    border: "1.5px solid #bbf7d0",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: "nowrap",
    transition: "background 0.15s",
  },
  message: { marginTop: 14, fontWeight: 600, fontSize: 14 },

  // ── Modal ─────────────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.5)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backdropFilter: "blur(4px)",
  },
  modalBox: {
    background: "#fff",
    borderRadius: 14,
    width: "min(96vw, 900px)",
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 24px 60px rgba(15,23,42,0.25)",
    overflow: "hidden",
    border: "1px solid #e2e8f0",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "18px 22px",
    borderBottom: "1px solid #e2e8f0",
    background: "linear-gradient(135deg, #faf5ff, #eff6ff)",
  },
  modalTitle: { fontSize: 16, fontWeight: 700, color: "#6d28d9" },
  modalSubtitle: { fontSize: 12, color: "#64748b", marginTop: 2 },
  modalClose: {
    background: "#f1f5f9",
    border: "none",
    fontSize: 16,
    cursor: "pointer",
    color: "#64748b",
    lineHeight: 1,
    padding: "4px 8px",
    borderRadius: 6,
    transition: "background 0.15s",
  },
  modalBody: { padding: "18px 22px", overflowY: "auto", flex: 1 },
  modalStatus: {
    textAlign: "center",
    color: "#94a3b8",
    padding: "40px 0",
    fontSize: 14,
  },

  // ── Warehouse table ───────────────────────────────────────
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
    minWidth: 700,
  },
  th: {
    padding: "10px 12px",
    background: "linear-gradient(135deg, #6d28d9, #4f46e5)",
    color: "#fff",
    textAlign: "left",
    fontWeight: 600,
    whiteSpace: "nowrap",
    fontSize: 12,
    letterSpacing: "0.04em",
  },
  td: {
    padding: "8px 12px",
    borderBottom: "1px solid #f1f5f9",
    whiteSpace: "nowrap",
    fontSize: 13,
    color: "#334155",
  },
  tdIn: { color: "#16a34a", fontWeight: 700, textAlign: "right" },
  tdOut: { color: "#dc2626", fontWeight: 700, textAlign: "right" },
  tdStock: { fontWeight: 700, textAlign: "right", color: "#6d28d9" },
};

export default styles;